# Site settings
title: Integrative Family Care at the Springs
email: integrativefamilycare@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Treating the body, mind, and spirit. Holistic care, naturopathy,
  homeopathy, chinese medicine, chiropractic care, nutrition, diet, wellness.
  Serving Rochester, Syracuse, Ithaca and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ifcats.net" # the base hostname & protocol for your site
exclude: [README.md, CNAME]
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
sass:
  style: compressed
