# Site settings
title: Integrative Family Care at the Springs
email: integrativefamilycare@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Integrative Family Care at the Springs. Taking a holistic approach to
  medicine, involving treating the body, mind, and spirit. Naturopathy,
  homeopathy, chinese medicine, chiropractic care, nutrition, diet, wellness.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ifcats.net" # the base hostname & protocol for your site
exclude: [README.md, CNAME]
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
sass:
  style: compressed
